import { createClient } from '@supabase/supabase-js';
import { createReadStream } from 'fs';
import { resolve } from 'path';

const supabase = createClient(
  'https://lhnogjmeyqbuoiruykpw.supabase.co',
  'sb_publishable_t4svZ8krxb9VqkPA0epoDQ_s-av_vnE'
);

const CSV_PATH = resolve('full_data.csv'); // generated by generate_csv.mjs
const BATCH_SIZE = 1000;

async function clearTable() {
  console.log('🚮 Deleting existing records...');
  // Supabase tables use UUID primary keys, so we delete without a numeric filter.
  const { error, count } = await supabase.from('book_section_employees')
    .delete()
    .neq('id', null)
    .select('id', { count: 'exact' });
  if (error) {
    console.error('❌ Delete error:', error.message);
    process.exit(1);
  }
  console.log(`✅ Deleted ${count ?? 0} rows`);
}

function parseCsvLine(line) {
  // Simple split by comma – assumes no commas inside quoted fields
  // Trim possible surrounding quotes
  return line.split(',').map(v => v.replace(/^"|"$/g, '').trim());
}

async function insertBatch(rows) {
  const { error, count } = await supabase.from('book_section_employees').upsert(rows, { returning: 'minimal' }).select('id', { count: 'exact' });
  if (error) {
    console.error('❌ Upsert error on batch:', error.message);
    process.exit(1);
  }
  console.log(`   ↦ Inserted ${count ?? rows.length} rows`);
}

async function run() {
  await clearTable();

  console.log('📥 Reading CSV:', CSV_PATH);
  const stream = createReadStream(CSV_PATH, { encoding: 'utf8' });
  let buffer = '';
  let isHeader = true;
  let header = [];
  let batch = [];
  let total = 0;

  for await (const chunk of stream) {
    buffer += chunk;
    let lines = buffer.split('\n');
    // Keep incomplete last line in buffer
    buffer = lines.pop() || '';
    for (const line of lines) {
      if (!line.trim()) continue;
      if (isHeader) {
        header = parseCsvLine(line);
        isHeader = false;
        continue;
      }
      const values = parseCsvLine(line);
      const obj = {};
      header.forEach((col, i) => (obj[col] = values[i]));
      batch.push(obj);
      if (batch.length >= BATCH_SIZE) {
        await insertBatch(batch);
        total += batch.length;
        batch = [];
      }
    }
  }
  // Process any remaining data in buffer
  if (buffer.trim()) {
    const line = buffer.trim();
    if (!isHeader) {
      const values = parseCsvLine(line);
      const obj = {};
      header.forEach((col, i) => (obj[col] = values[i]));
      batch.push(obj);
    } else {
      header = parseCsvLine(line);
    }
  }
  if (batch.length) {
    await insertBatch(batch);
    total += batch.length;
  }
  console.log(`✅ Finished importing. Total rows inserted: ${total}`);
}

run().catch(e => console.error('❌ Unexpected error:', e));
